# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xGocOd4pJw8_f24vVJGRgqEHhjp5xAJV

#Random Forest
"""

from keras.datasets import cifar10
import matplotlib.pyplot as plt

(X_train, y_train), (X_test, y_test)= cifar10.load_data()

X_train = X_train[:10000]
X_valid = X_train[10000:20000]
y_train = y_train[:10000]
y_valid = y_train[10000:20000]
X_train, X_test = X_train/255, X_test/255
X_train = X_train.reshape(10000, 3*32*32)
X_test = X_test.reshape(10000, 3*32*32)
y_train, y_test = y_train.flatten(), y_test.flatten()

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

import time
start_time = time.time()

rf = RandomForestClassifier(n_estimators=200,criterion='gini', max_depth=100, max_features='sqrt', min_samples_leaf=2,bootstrap = True)
rf.fit(X_train, y_train)
pred = rf.predict(X_test)
accuracy_score(y_test, pred)

print(time.time()-start_time)